name: flutter_stock_management_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  fluent_ui: ^4.1.5
  flutter:
    sdk: flutter
  get: 4.6.5
  bitsdojo_window: ^0.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/images/svg/
    # - assets/fonts/
    # - assets/lotties/
    # - assets/jsons/

