name: flutter_stock_management_app
version: 1.0.0+1
publish_to: none
description: A new Stocker App Flutter project.

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  excel: ^4.0.0
  flutter:
    sdk: flutter
  get: 4.6.6
  get_storage: ^2.1.1
  syncfusion_flutter_core: ^23.2.7
  syncfusion_flutter_datagrid: ^23.2.7
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: 2.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    #- assets/images/svg/
    - assets/fonts/
    #- assets/lotties/
    - assets/jsons/
    - assets/kitap.xlsx

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
